### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by oleksharh** [oleksharh/my-portfolio-website#10]

**Comment by MindfulLearner** [comment]
do you need help?

**Comment by oleksharh** [comment]
> do you need help?

Hey, no everything in this repo is for the uni assignment and I am able to do it myself, I have been told to do it this way. Though thanks for offering me your help

**Comment by MindfulLearner** [comment]
Oh sorry i've foudn the issue in some website good first issue good job anyway!

**Comment by oleksharh** [comment]
Well maybe if you really willing to add footer on all the pages except the projects_detailed.html, I could potentially merge your PR, as I don't think it will go against my assignment brief tasks/rules. It shouldn't take long, but note that there is some ambiguity in classes namings and some of the variables. If you will not be doing this, I will remove lable as i missclicked on it and apologize for adding it on the issue. Let me know if you are willing to take this?

**Comment by MindfulLearner** [comment]
I think that if you merge something by someone else could a nice thing, since open source is well seen by HR and Developers.

I'll do it!

**Comment by MindfulLearner** [comment]
can you do a new issue with that info then assign me ty!

**Comment by oleksharh** [comment]
Okay, will do it in a few minutes, will close this issue as soon as I open a new one with a description and drop a comment here to let you know

**Comment by oleksharh** [comment]
Opened new issue, will assign you to it in a moment
