### ISSUE TITLE
Add Footer to Website

### ISSUE THREAD

**Issue by oleksharh** [oleksharh/my-portfolio-website#12]
# Task Specification: Add Footer to Website  

## Objective  
Create a footer that adheres to the existing website design and functional requirements.  

---

## Footer Design Specifications  
1. **Layout**: 
   - The footer should be a single row.  
   - Include the following elements:  
     - Copyright notice: `@ OLEKSHARH 2024`.  
     - Links to:
       - LinkedIn.
       - GitHub.
       - `mailto` link for contact.  

2. **Styling**:  
   - Use a `2px outline` for elements, with colors defined in `variables.css` (theme-dependent; utilize variables for colors).  
   - The copyright notice is plain text with no effects, matching the current page's font.  
   - Links should match the size of the navbar links.  
   - Links should have the following hover effect:  
     ```css
     transition: .2s transform ease-in-out;
     transform: scale(1.2);
     ```

3. **Behavior**:  
   - Footer is visible only at the bottom of the page (not fixed).  
   - Ensure the **lower navbar** (which rolls out when scrolled down) does not cover the footer.  

---

## Technical Constraints  
1. **Tools**:  
   - Use only plain HTML, CSS, and JavaScript.  
   - Do not use any external libraries, frameworks, or extensions.  

2. **File Restrictions**:  
   - No modifications to `projects_detailed.html`.  
   - Use `navbars.css` as a reference for maintaining design consistency.  

---

## Deliverables  
1. A fully functional footer integrated into the website.  
2. Ensure all modifications adhere to the outlined constraints and styling rules.  

---

## Testing  
1. Validate that the footer is visible only at the bottom of the page.  
2. Confirm that the **lower navbar** does not obscure the footer at any time.  

---

## Additional Notes  
- Provide clear comments in the code where necessary.  
- Push the changes to a new branch and create a pull request for review.

**Comment by MindfulLearner** [comment]
I'll do this issue!

**Comment by MindfulLearner** [comment]
Hello!

I have an idea, but I need more information to know if I'm on the right track.

https://github.com/user-attachments/assets/fbbee601-ace7-4504-b3ff-a98fc88bf3bf

![image](https://github.com/user-attachments/assets/a5f9e777-d7e5-4009-a03f-448582bcfc43)

The navBar has to be above or below the footer?

Waiting for your feedback! So i can move forward.

**Comment by oleksharh** [comment]
Footer has to be lower than the lower navbar and they have to have some gap between each other

**Comment by MindfulLearner** [comment]
to apply to every page right?
https://github.com/user-attachments/assets/5b86f6a5-6332-49d3-af6f-19baa87c7a2d

**Comment by MindfulLearner** [comment]
Every other page is 100vh so will only need the footer i think.

**Comment by MindfulLearner** [comment]
https://github.com/user-attachments/assets/9adbcf03-3a98-4619-8f82-e62b3bfecaa0

**Comment by oleksharh** [comment]
I will add more information to the page and nearly all of them will be more than 100vh, so I would like to keep that lower navbar, it anyway can be removed at any moment though. Thanks

**Comment by MindfulLearner** [comment]
Ok perfect, ill open a PR! ty for the contribution. Hope your assignment will be nice, anyway have you asked to your teacher if open source like this is okay

**Comment by oleksharh** [comment]
Thanks for help. In terms of whether I am allowed to accept contributions I have no idea, plus it's Sunday today so no one would give me a response, and provided that we were told to use github I believe they should be totally okay with that. Thanks for help agian!

**Comment by MindfulLearner** [comment]
Yeah, I think it's a good thing. As I said earlier, open source is well seen by everyone! See ya!
